name: Build Image and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name'
        required: true
        default: 'v0.2.0'
        type: string
      push_to_ghcr:
        description: 'Push Docker image to GitHub Container Registry (GHCR)'
        required: false
        default: true
        type: boolean
      build_sif:
        description: 'Build Apptainer (SIF) image'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:


      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if tag already exists
        run: |
          TAG_NAME="${{ github.event.inputs.tag_name }}"
          echo "Checking if tag '$TAG_NAME' already exists..."
          
          # Check if tag exists locally or remotely
          if git tag -l | grep -q "^${TAG_NAME}$"; then
            echo "❌ Error: Tag '$TAG_NAME' already exists locally!"
            exit 1
          fi
          
          # Check if tag exists on remote
          if git ls-remote --tags origin | grep -q "refs/tags/${TAG_NAME}$"; then
            echo "❌ Error: Tag '$TAG_NAME' already exists on remote!"
            exit 1
          fi
          
          echo "✅ Tag '$TAG_NAME' does not exist. Proceeding with build..."
      
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2

      - name: Login to GitHub Container Registry
        if: ${{ github.event.inputs.push_to_ghcr }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run download script
        run: |
          echo "Start Downloading"
          chmod +x download.sh
          ./download.sh

      - name: Run build script
        run: |
          echo "Start Building"
          chmod +x build.sh
          
          # Extract CUDA base image tag from Dockerfile
          CUDA_TAG=$(grep -oP 'FROM nvidia/cuda:\K[^ ]+' Dockerfile)
          echo "Extracted CUDA_TAG: $CUDA_TAG"
          
          REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME_LOWER=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          BUILD_COMMAND="./build.sh --rmi --tag=ghcr.io/${REPO_OWNER_LOWER}/${REPO_NAME_LOWER}:${{ github.event.inputs.tag_name }}-cuda-${CUDA_TAG}"
          if ${{ github.event.inputs.push_to_ghcr == true }}; then
            BUILD_COMMAND+=" --push"
          fi
          if ${{ github.event.inputs.build_sif == true }}; then
            BUILD_COMMAND+=" --sif"
          fi
          
          echo "Running build command: $BUILD_COMMAND"
          eval "$BUILD_COMMAND"
          
          # Only execute apptainer command if SIF was built
          if ${{ github.event.inputs.build_sif == true }}; then
            apptainer exec --no-init ai-dev-env.sif bash -c "echo 'Build completed successfully!'"
          fi

      - name: Split SIF file into volumes
        if: ${{ github.event.inputs.build_sif == true }}
        run: |
          echo "Splitting SIF file into 1900MB volumes..."
          split -b 1900M ai-dev-env.sif ai-dev-env.sif.part.
          rm ai-dev-env.sif
          ls -la ai-dev-env.sif.part.*

      - name: Generate release notes
        id: release_notes
        run: |
          chmod +x generate-release-notes.sh
          ./generate-release-notes.sh \
            --tag "${{ github.event.inputs.tag_name }}" \
            --repo-owner "${{ github.repository_owner }}" \
            --repo-name "${{ github.event.repository.name }}" \
            --build-sif "${{ github.event.inputs.build_sif }}" \
            --output "release_body.md"

      - name: Create Release and Upload Files
        uses: softprops/action-gh-release@v1
        with:
          name: AI Development Environment ${{ github.event.inputs.tag_name }}
          files: |
            ${{ github.event.inputs.build_sif == true && 'ai-dev-env.sif.part.*' || '' }}
          tag_name: ${{ github.event.inputs.tag_name }}
          body_path: release_body.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
